pipeline:
  name: glhf2
  identifier: glhf
  projectIdentifier: Shantelle_Test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: testStage
        identifier: testStage
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: sample_service_1674797546369
          environment:
            environmentRef: dev_1674814771811
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devcluster_1674814771811
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: test
        identifier: test
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: Deploy_Sample_Pipeline_1674797564693
          project: Shantelle_Test
          outputs:
            - name: test
              value: <+proj.name>
  variables:
    - name: testVar
      type: String
      description: ""
      value: <+input>
